// nuxt-version/components/alert/alert.vue
<script setup>
import { ref, watch, onUnmounted } from 'vue';

// Props
const { type, message, duration } = defineProps({
  type: {
    type: String,
    required: true,
    validator: (value) =>
      ['success', 'danger', 'warning', 'info'].includes(value),
  },
  message: {
    type: String,
    required: true,
  },
  duration: {
    type: Number,
    default: 3000,
  },
});

// State and Refs
const visible = ref(false);
const alertRef = ref(null);

// Methods
let timeout;

watch(
  () => message,
  (newMessage) => {
    if (newMessage) {
      visible.value = true;

      // Automatically close the alert after the specified duration
      clearTimeout(timeout); // Clear any previous timeout
      timeout = setTimeout(() => {
        visible.value = false; // Hide the alert
      }, duration);
    }
  }
);

onUnmounted(() => {
  // Cleanup timeout when component is unmounted
  clearTimeout(timeout);
});
</script>

<template>
  <div
    ref="alertRef"
    class="alert floating-alert"
    :class="[
      `alert-${type}`,
      'alert-dismissible',
      'fade',
      visible ? 'show' : 'd-none',
    ]"
    role="alert"
  >
    <strong>{{ message }}</strong>
  </div>
</template>

<style scoped lang="scss">
@import '../../node_modules/bootstrap/scss/functions';
@import '../../node_modules/bootstrap/scss/mixins';
@import '../../node_modules/bootstrap/scss/variables';
@import '../../node_modules/bootstrap/scss/alert';

.floating-alert {
  position: fixed;
  top: 20px;
  right: 20px;
  z-index: 3;
}
</style>

// next-version/src/app/components/alert/alert.tsx
import './alert.scss';
import React, { JSX, useEffect, useRef, useState } from 'react';

interface AlertProps {
  type: 'success' | 'danger' | 'warning' | 'info';
  message: string;
  duration?: number;
}

export function AlertComponent({
  type,
  message,
  duration = 3000,
}: AlertProps): JSX.Element {
  const [visible, setVisible] = useState(false);
  const alertRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (message) {
      setVisible(true); // Show the alert

      // Initialize Bootstrap Alert JS behavior
      if (alertRef.current) {
        // Automatically close the alert after the specified duration
        const timeout = setTimeout(() => {
          setVisible(false); // Reset visibility after closing
        }, duration);

        return () => clearTimeout(timeout); // Cleanup timeout on unmount
      }
    }
  }, [message, duration]); // Re-run effect whenever message or duration changes

  return (
    <div
      ref={alertRef}
      className={`alert floating-alert alert-${type} alert-dismissible fade ${visible ? 'show' : 'd-none'}`}
      role="alert"
    >
      <strong>{message}</strong>
    </div>
  );
}
