// nuxt-version/components/user/login.vue
<script setup>
import { ref } from 'vue';

const formData = ref({ email: '', password: '' });
const error = ref(false);
const success = ref(false);
const errorMessage = ref('');
const userId = useState('login', () => null);

async function handleSubmit(e) {
  try {
    e.preventDefault();
    await $fetch('/api/login', {
      method: 'POST',
      body: formData.value,
    });
    success.value = true;
    const userCookie = useCookie('user');
    userId.value = userCookie.value;
  } catch (err) {
    console.error('Error:', err);
    error.value = true;
    errorMessage.value = err.message;
  }
}
</script>

<template>
  <div class="container mt5">
    <h1>Login</h1>
    <form class="mt-3" action="#" @submit="handleSubmit">
      <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input
          id="email"
          v-model="formData.email"
          type="email"
          class="form-control"
          required
        />
      </div>
      <div class="mb-3">
        <label html="password" class="form-label">Password</label>
        <input
          id="password"
          v-model="formData.password"
          type="password"
          class="form-control"
          required
        />
      </div>
      <div v-if="error" class="alert alert-danger">{{ errorMessage }}</div>
      <div v-if="success" class="alert alert-success">
        User login successfully!
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</template>

<style lang="scss">
@import '../../node_modules/bootstrap/scss/functions';
@import '../../node_modules/bootstrap/scss/mixins';
@import '../../node_modules/bootstrap/scss/variables';
@import '../../node_modules/bootstrap/scss/forms';
@import '../../node_modules/bootstrap/scss/buttons';
@import '../../node_modules/bootstrap/scss/alert';
</style>

// src/app/components/user/login.tsx
"use client";

import './user.scss';
import { useState } from "react";
import { loginUser } from "./actions";

export default function LoginUserForm() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);

    try {
      const result = await loginUser({ email, password });

      if (result.success) {
        setSuccess("User login successfully!");
        setEmail("");
        setPassword("");
      } else {
        setError(result.error);
      }
    /* eslint-disable  @typescript-eslint/no-explicit-any */
    } catch (err: any) {
      setError("An unexpected error occurred. Please try again.");
      console.error(err);
    }
  };

  return (
    <div className="container mt-5">
      <h1>Login</h1>
      <form onSubmit={handleSubmit} className="mt-3">
        <div className="mb-3">
          <label htmlFor="email" className="form-label">Email address</label>
          <input
            type="email"
            className="form-control"
            id="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="password" className="form-label">Password</label>
          <input
            type="password"
            className="form-control"
            id="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>

        {error && <div className="alert alert-danger">{error}</div>}
        {success && <div className="alert alert-success">{success}</div>}

        <button type="submit" className="btn btn-primary">Login</button>
      </form>
    </div>
  );
}
