// nuxt-version/components/search/search.vue
<script setup>
import { ref } from 'vue';
import BooksComponent from '../book/book.vue';

// State variables
const books = ref([]);
const search = ref('');
const isLoading = ref(false);

async function performSearch() {
  isLoading.value = true;
  books.value = [];
  try {
    const response = await fetch(`/api/search?q=${search.value}`);
    const data = await response.json();
    books.value = data?.docs || [];
  } catch (error) {
    console.error(error);
  } finally {
    isLoading.value = false;
  }
}
</script>

<template>
  <div class="container">
    <div class="row">
      <!-- Search Input -->
      <div class="col-8">
        <div class="form-floating mb-3">
          <input
            id="search"
            v-model="search"
            type="text"
            class="form-control"
            placeholder="name@example.com"
          />
          <label for="search">Enter your research</label>
        </div>
      </div>
      <!-- Search Button -->
      <div class="col-4">
        <button type="button" class="btn btn-primary" @click="performSearch">
          Search!
        </button>
      </div>
    </div>

    <!-- Spinner -->
    <div v-if="isLoading" class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>

    <!-- Book List -->
    <BooksComponent
      v-if="books.length > 0"
      :books="books"
      :search-result="true"
    />
  </div>
</template>

<style lang="scss" scoped>
@import '../../node_modules/bootstrap/scss/functions';
@import '../../node_modules/bootstrap/scss/mixins';
@import '../../node_modules/bootstrap/scss/variables';
@import '../../node_modules/bootstrap/scss/forms';
@import '../../node_modules/bootstrap/scss/buttons';
@import '../../node_modules/bootstrap/scss/spinners';
</style>

// src/app/components/search/search.tsx
"use client";

import './search.scss';
import { useState } from "react";
import type { Book } from "@/app/services/open-library/dto/open-library.dto";
import { BooksComponent } from "../books/books";

export function SearchComponent() {
    const [books, setBooks] = useState<Book[]>([]);
    const [search, setSearch] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    return(
        <div className="container">
            <div className="row">
                <div className="col-8">
                    <div className="form-floating mb-3">
                        <input type="email" className="form-control" id="search" placeholder="name@example.com" onChange={(event) => setSearch(event.target.value)} />
                        <label htmlFor="search">Enter your research</label>
                    </div>
                </div>
                <div className="col-4">
                    <button type="button" className="btn btn-primary" onClick={async (event) => {
                        setIsLoading(true);
                        setBooks([]);
                        setBooks(await searchBooks(event, search));
                        setIsLoading(false);
                    }}>Primary</button>
                </div>
                {isLoading && <Spinner />}
                {books.length > 0 && listBooks(books)}
            </div>
        </div>
    )
}

function Spinner() {
    return (
        <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Loading...</span>
        </div>
    )
}

function listBooks(books: Array<Partial<Book>>) {
    return (
        <BooksComponent books={books} searchResult={true} />
    )
}

async function searchBooks(e: React.MouseEvent, prmSearch: string) {
    e.preventDefault();
    try {
        const response = await fetch(`/api/search?q=${prmSearch}`);
        const data = await response.json();
        return data?.docs;
    } catch (error) {
        console.error(error);
    }
}
